/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.dostojic.climbers.swing.bff;

import com.dostojic.climbers.logic.Controller;
import java.awt.Color;

/**
 *
 * @author dejan
 */
public class FServer extends javax.swing.JFrame {

    volatile ServerThread serverThread;
    Controller controller;
    /**
     * Creates new form FServer
     */
    public FServer(Controller controller) {
        initComponents();
        this.controller = controller;
        serverThread = new ServerThread(controller);
        labelServerStatus.setVisible(false);
        buttonStopServer.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        butStartServer = new javax.swing.JButton();
        labelServerStatus = new javax.swing.JLabel();
        buttonStopServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        butStartServer.setText("Pokrenite server");
        butStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butStartServerActionPerformed(evt);
            }
        });

        labelServerStatus.setText("Server startovan!");

        buttonStopServer.setText("Zaustavi server");
        buttonStopServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopServerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonStopServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butStartServer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelServerStatus)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butStartServer)
                    .addComponent(labelServerStatus))
                .addGap(18, 18, 18)
                .addComponent(buttonStopServer)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butStartServerActionPerformed
        
        synchronized (serverThread) {
            if (serverThread.isAlive()) {
                System.out.println("Server is allready running.");
                return;
            }
        }

        serverThread = new ServerThread(controller);
        serverThread.start();

        butStartServer.setEnabled(false);
        labelServerStatus.setForeground(Color.green);
        labelServerStatus.setText("Pokrenut server!");
        labelServerStatus.setVisible(true);
        buttonStopServer.setEnabled(true);

    }//GEN-LAST:event_butStartServerActionPerformed

    private void buttonStopServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopServerActionPerformed
//        startServerThread.setRunServer(false);

        serverThread.stopEntireServer();

        buttonStopServer.setEnabled(false);
        butStartServer.setEnabled(true);
        labelServerStatus.setForeground(Color.red);
        labelServerStatus.setText("Zaustavljen server!");
    }//GEN-LAST:event_buttonStopServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void mainDisabled(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FServer(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butStartServer;
    private javax.swing.JButton buttonStopServer;
    private javax.swing.JLabel labelServerStatus;
    // End of variables declaration//GEN-END:variables
}
